import {rainfallText} from './weather-core.js?v=0.7.1';
import {createMap,createMarker} from './map-provider.js?v=0.7.1';
import {createPlaceSearch} from './open-places.js?v=0.7.1';
import {createNavigationUI} from './navigation-ui.js?v=0.7.1';
import {parkingHandoff,journeyForSelection} from './journey.js?v=0.7.1';
import {createParkingUI} from './parking-map-ui.js?v=0.7.1';
import {VERSION,finite,escapeHtml as esc,validPoint,parseCoordinates,weatherInfo,aqiInfo,normalizedSaved} from './core.js?v=0.7.1';
import {createLayers,jsonFetch} from './layers.js?v=0.7.1';
const $=id=>document.getElementById(id),fmt=(v,suffix='')=>finite(v)?Math.round(v)+suffix:'—';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('此瀏覽器無法儲存資料，請確認儲存空間');return false}};
const state={map:null,layers:null,panel:'',selected:null,selection:0,placeAbort:null,userPoint:null,saved:normalizedSaved(read('geodeck.saved',[])),layerStatuses:new Map(),route:null,routeMode:'driving',provider:'auto',routeSequence:0,routeOrigin:null,cameraTimer:null,cameraImage:null,cameraSequence:0,poiMarkers:[]};
let parkingController,poiSequence=0,poiScope="gps",routePick=null;
$('parking')?.addEventListener('click',()=>renderParking());
let toastTimer,selectionMarker,locationMarker;
const placeSearch=createPlaceSearch();
const nearbyPlaces=(type,p)=>placeSearch.nearby(type,p);
let navigationController,searchSequence=0;
let journey=read('geodeck.journey',null),parkedCar=read('geodeck.parked',null);
if(!validPoint(journey?.parking))journey=null;
if(!validPoint(parkedCar))parkedCar=null;
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4200)}
function stopCamera(){state.cameraSequence++;clearTimeout(state.cameraTimer);if(state.cameraImage){state.cameraImage.src='';state.cameraImage.remove();state.cameraImage=null}}
function openPanel(kind,title,html,eyebrow='GEODECK'){searchSequence++;if(state.panel==='routes'&&kind!=='routes')navigationController?.cancel();if(state.panel==='field')poiSequence++;if(state.panel==='camera')stopCamera();state.panel=kind;$('panel').dataset.kind=kind;$('panelEyebrow').textContent=eyebrow;$('panelTitle').textContent=title;$('panelBody').innerHTML=html;$('panel').classList.remove('hidden');document.body.classList.add('panel-open');for(const id of ['layers','routes','favorites'])$(id).setAttribute('aria-expanded',String(kind===id));$('panelBody').scrollTop=0}
function closePanel(){searchSequence++;if(state.panel==='field')poiSequence++;if(state.panel==='routes')navigationController?.cancel();if(state.panel==='camera')stopCamera();state.panel='';$('panel').classList.add('hidden');document.body.classList.remove('panel-open');for(const id of ['layers','routes','favorites'])$(id).setAttribute('aria-expanded','false')}
function loading(text='載入中…'){return `<p class="subtle" role="status">${esc(text)}</p>`}
function sourceLink(url,title){return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`}
function mapReady(){if(state.map)return true;toast(navigator.onLine?'地圖尚未載入，請稍候或重新開啟':'目前離線，仍可查看收藏與備註');return false}
function mapFailure(message){$('mapState').classList.remove('hidden');$('mapState').innerHTML=`<strong>地圖暫時無法開啟</strong><p>${esc(message)}</p><button class="button" id="retryMap">重新載入</button>`;$('retryMap').onclick=()=>location.reload()}
function renderLayers(){const on=state.layers?.enabled||new Set();const items=[['radar','☂','雷達回波','觀測時間軸'],['cloud','☁','衛星雲圖','依地區選擇衛星'],['camera','▣','即時影像','台灣公開道路與景點'],['aqi','≋','空氣品質','美國 AQI · 模式格點'],['earthquake','◉','近期地震','USGS · 過去 7 天']];
openPanel('layers','資訊圖層',`<p class="subtle">深色底圖 · Google Maps</p><div class="layer-grid">${items.map(([id,icon,title,note])=>`<button class="layer-card" data-layer="${id}" aria-pressed="${on.has(id)}"><span class="symbol" aria-hidden="true">${icon}</span><b>${title}</b><small>${note}</small></button>`).join('')}</div><div id="layerDetails">${layerDetails()}</div><p class="micro">圖層依來源涵蓋範圍顯示；空白不代表沒有天氣或事件。地震紀錄沒有即時預警功能。</p>`,'MAP LAYERS')}
function layerDetails(){return [...state.layerStatuses].filter(([id])=>state.layers?.enabled.has(id)).map(([id,s])=>`<p class="micro">${esc(s)}</p>`).join('')}
function updateLayerStatus(id,message,on){if(on)state.layerStatuses.set(id,message);else state.layerStatuses.delete(id);$('layerBadges').innerHTML=[...state.layerStatuses].map(([id,s])=>`<span>${esc(s)}</span>`).join('');const count=state.layers?.enabled.size||0;$('layerCount').textContent=count;$('layerCount').classList.toggle('hidden',!count);if(state.panel==='layers'&&$('layerDetails'))$('layerDetails').innerHTML=layerDetails()}
function renderRadar(data){$('radarControl').classList.toggle('hidden',!data);if(!data)return;$('radarRange').max=data.frames.length-1;$('radarRange').value=data.index;$('radarPlay').textContent=data.playing?'Ⅱ':'▶';$('radarPlay').setAttribute('aria-label',data.playing?'暫停雷達':'播放雷達');const t=data.frames[data.index].time*1000;$('radarTime').textContent=new Date(t).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})+' · 雷達回波';$('radarSource').textContent='RainViewer · 合成時間（手機時區）'}
function coords(p){return p.lat.toFixed(5)+', '+p.lng.toFixed(5)}
function isSaved(p){return state.saved.some(s=>Math.abs(s.lat-p.lat)<.00001&&Math.abs(s.lng-p.lng)<.00001)}
async function selectLocation(p,{pan=false}={}){if(!validPoint(p))return;state.selected={...p,title:p.title||'選取位置'};const token=++state.selection;state.placeAbort?.abort();state.placeAbort=new AbortController();if(state.map){selectionMarker?.setMap(null);selectionMarker=createMarker({map:state.map,position:p,title:state.selected.title,icon:{scale:9,fillColor:'#b8c7d6',fillOpacity:1,strokeColor:'#17291b',strokeWeight:3},zIndex:100});if(pan){state.map.panTo(p);state.map.setZoom(Math.max(14,state.map.getZoom()))}}
openPanel('place',state.selected.title,`<p class="location-meta" id="placeCoords">${coords(p)}</p><div class="actions"><button class="button primary" data-action="route-selected">↗ 前往這裡</button><button class="button" data-action="save-selected">${isSaved(p)?'✓ 已收藏':'☆ 收藏'}</button><button class="button" data-action="share-selected">分享</button></div><div id="weatherContent">${loading('讀取逐時天氣…')}</div><div id="aqiContent">${loading('讀取空氣品質…')}</div><div class="actions"><button class="button" data-action="nearby-parking">附近停車</button><button class="button" data-action="nearby-cameras">附近影像</button><button class="button" data-action="nearby-facilities">附近設施</button></div>`,'LOCATION');
const still=()=>token===state.selection&&state.panel==='place';
loadWeather(p,state.placeAbort.signal).then(d=>{if(still())renderWeather(d)}).catch(e=>{if(still()&&e.name!=='AbortError')$('weatherContent').innerHTML='<p class="error">天氣暫時無法取得，請稍後重新點選位置。</p>'});
loadAqi(p,state.placeAbort.signal).then(d=>{if(still())renderAqi(d)}).catch(e=>{if(still()&&e.name!=='AbortError')$('aqiContent').innerHTML='<p class="error">空氣品質暫時無法取得。</p>'});
}
const weatherCache=new Map();
async function loadWeather(p,signal){const key=p.lat.toFixed(3)+','+p.lng.toFixed(3);const cache=weatherCache.get(key);if(cache&&Date.now()-cache.at<600000)return cache.data;const q=new URLSearchParams({latitude:p.lat,longitude:p.lng,current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m',hourly:'temperature_2m,precipitation_probability,precipitation,weather_code',daily:'sunrise,sunset,uv_index_max',forecast_days:'2',timezone:'auto',timeformat:'unixtime'});const d=await jsonFetch('https://api.open-meteo.com/v1/forecast?'+q,16000,signal);weatherCache.set(key,{at:Date.now(),data:d});if(weatherCache.size>25)weatherCache.delete(weatherCache.keys().next().value);return d}
async function loadAqi(p,signal){const q=new URLSearchParams({latitude:p.lat,longitude:p.lng,current:'us_aqi,pm2_5,pm10',timezone:'auto',timeformat:'unixtime'});return jsonFetch('https://air-quality-api.open-meteo.com/v1/air-quality?'+q,16000,signal)}
function localTime(timestamp,zone,withDate=false){if(!finite(timestamp))return'—';try{return new Intl.DateTimeFormat('zh-TW',{timeZone:zone||'UTC',hour:'2-digit',minute:'2-digit',hourCycle:'h23',...(withDate?{month:'numeric',day:'numeric'}:{})}).format(new Date(timestamp*1000))}catch{return new Date(timestamp*1000).toISOString().slice(11,16)+' UTC'}}
function renderWeather(d){const c=d.current||{},[label,icon]=weatherInfo(c.weather_code),h=d.hourly||{},daily=d.daily||{};let hours='';for(let i=0,n=0;i<(h.time||[]).length&&n<24;i++){if(h.time[i]<Math.floor(Date.now()/3600000)*3600)continue;const [text,symbol]=weatherInfo(h.weather_code[i]);hours+=`<div class="hour"><small>${localTime(h.time[i],d.timezone)}</small><span class="weather-icon" aria-label="${text}">${symbol}</span><b>${fmt(h.temperature_2m[i],'°')}</b><span class="rain" title="降雨機率">${fmt(h.precipitation_probability?.[i],'%')}</span><span class="rain-amount" title="該時段預報降水量">${rainfallText(h.precipitation?.[i])}</span></div>`;n++}
$('weatherContent').innerHTML=`<div class="weather-summary"><div class="metric"><span class="label">${icon} ${label}</span><div class="value">${fmt(c.temperature_2m,'°')} <span>C</span></div><div class="detail">體感 ${fmt(c.apparent_temperature,'°')} · 濕度 ${fmt(c.relative_humidity_2m,'%')}</div></div><div class="metric"><span class="label">風速／風向</span><div class="value">${fmt(c.wind_speed_10m)} <span>km/h</span></div><div class="detail">${windDirection(c.wind_direction_10m)} · ${fmt(c.wind_direction_10m,'°')}</div></div></div><h2>未來 24 小時 <span class="subtle">· ${esc(d.timezone||'UTC')} 當地時間</span></h2><div class="hourly" aria-label="逐時氣溫、降雨機率與雨量">${hours||'<p class="subtle">暫無逐時資料</p>'}</div><p class="micro">% 為降雨機率；mm 為該時刻前一小時的預報降水量（雨、陣雨與雪水當量），不是實測累積雨量。</p><div class="weather-more"><div><span>日出／日落</span>${localTime(daily.sunrise?.[0],d.timezone)} / ${localTime(daily.sunset?.[0],d.timezone)}</div><div><span>今日最高紫外線指數</span>${fmt(daily.uv_index_max?.[0])}</div></div><p class="micro forecast-note">${sourceLink('https://open-meteo.com/','Open-Meteo')} · 數值模式預報<br>資料時刻：${localTime(c.time,d.timezone,true)}（當地時間）${Date.now()-c.time*1000>7200000?' · 資料較舊':''}</p>`;
$('centerLabel').textContent=`${fmt(c.temperature_2m,'°')} ${label} · 已選位置`}
function windDirection(v){return finite(v)?['北','東北','東','東南','南','西南','西','西北'][Math.round(v/45)%8]+'風':'—'}
function renderAqi(d){const c=d.current||{},info=aqiInfo(c.us_aqi);$('aqiContent').innerHTML=`<h2>空氣品質</h2><div class="metric aqi" style="--aqi:${info.color}"><div class="row"><div><div class="label">美國 AQI · ${info.label}</div><div class="value">${fmt(c.us_aqi)}</div></div><div class="detail">PM2.5 ${fmt(c.pm2_5)} µg/m³<br>PM10 ${fmt(c.pm10)} µg/m³</div></div></div><p class="micro">${sourceLink('https://open-meteo.com/en/docs/air-quality-api','Open-Meteo／CAMS')} · 模式估計，非現地測站<br>資料時刻：${localTime(c.time,d.timezone,true)}（當地時間）${Date.now()-c.time*1000>10800000?' · 資料較舊':''}</p>`}
function renderFavorites(){openPanel('favorites','我的收藏',`${parkedCar?`<div class="journey-card"><h2>我的停車位置</h2><p class="micro">記錄於 ${esc(new Date(parkedCar.savedAt).toLocaleString('zh-TW'))}</p><div class="actions"><button class="button" data-action="car-open">查看位置</button><button class="button" data-action="car-route">走回車位</button><button class="text-button" data-action="car-clear">清除</button></div></div>`:'<button class="button full" data-action="car-save">◎ 記住目前停車位置</button>'}<p class="subtle">儲存在這台裝置。離線也能查看地點與備註。</p>${state.saved.length?state.saved.map((p,i)=>`<article class="saved-item"><button class="saved-open" data-saved-open="${i}">${esc(p.title)}</button><p>${coords(p)}${p.note?'\n'+esc(p.note):''}</p><div class="saved-actions"><button class="text-button" data-saved-edit="${i}">編輯</button><button class="text-button" data-saved-route="${i}">前往</button><button class="text-button" data-saved-delete="${i}">移除</button></div></article>`).join(''):'<div class="empty"><strong>把想去的地方留在這裡</strong>搜尋或點選地圖上的位置，按「收藏」。</div>'}<div class="actions"><button class="button" data-action="export-favorites">匯出備份</button><label class="button">匯入備份<input id="importFavorites" type="file" accept="application/json,.json" hidden></label></div>`,'SAVED PLACES');$('importFavorites').onchange=importFavorites}
function editSaved(p){const existing=state.saved.find(s=>Math.abs(s.lat-p.lat)<.00001&&Math.abs(s.lng-p.lng)<.00001);openPanel('edit','收藏地點',`<form id="savedForm"><label class="form-field">名稱<input id="savedName" maxlength="120" required value="${esc(existing?.title||p.title)}"></label><p class="subtle">${coords(p)}</p><label class="form-field">備註<textarea id="savedNote" maxlength="4000" placeholder="例如：集合位置、出口、開放時間">${esc(existing?.note||'')}</textarea></label><button class="button primary full" type="submit">儲存收藏</button></form>`,'SAVED PLACES');$('savedForm').onsubmit=e=>{e.preventDefault();const item={...p,id:existing?.id||coords(p),title:$('savedName').value.trim()||'收藏地點',note:$('savedNote').value.trim(),savedAt:existing?.savedAt||new Date().toISOString()};const next=[item,...state.saved.filter(s=>s!==existing)].slice(0,200);if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已儲存收藏')}}}
function exportFavorites(){const blob=new Blob([JSON.stringify({app:'GeoDeck',version:VERSION,exportedAt:new Date().toISOString(),places:state.saved},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='geodeck-favorites.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importFavorites(e){const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024)return toast('備份檔案太大');try{const d=JSON.parse(await file.text()),raw=Array.isArray(d)?d:d.places;if(!Array.isArray(raw)||!raw.every(validPoint))throw Error();const next=normalizedSaved([...state.saved,...raw]);if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已合併收藏，重複座標保留原有備註')}}catch{toast('無法讀取這個收藏備份')}}
async function shareSelected(){const p=state.selected;if(!p)return;const u=new URL('./',location.href);u.searchParams.set('lat',p.lat.toFixed(6));u.searchParams.set('lng',p.lng.toFixed(6));u.searchParams.set('name',p.title.slice(0,120));try{if(navigator.share)await navigator.share({title:p.title,url:u.href});else{await navigator.clipboard.writeText(u.href);toast('地點連結已複製')}}catch(e){if(e.name!=='AbortError')toast('分享未完成，可在收藏中保留座標')}}
function renderRoutes(){navigationController.render()}
function showCamera(c,alternatives=[c],catalogTime=''){state.selected={lat:c.lat,lng:c.lng,title:c.name};openPanel('camera',c.name,`${alternatives.length>1?`<label class="form-field">同位置的影像<select id="cameraChoice">${alternatives.map((v,i)=>`<option value="${i}">${esc(v.name)}</option>`).join('')}</select></label>`:''}<div class="camera-frame" id="cameraFrame"><span class="camera-loading" id="cameraLoading">正在連接公開影像…</span></div><p class="micro" id="cameraStatus" role="status">來源連線中</p><div class="actions"><button class="button" data-action="route-selected">前往這裡</button><button class="button" id="refreshCamera">重新整理</button></div><a class="button full" href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">在原站觀看 ↗</a><p class="micro">目錄來源：${sourceLink('https://www.twipcam.com/','台灣即時影像 twipcam')}<br>目錄取得：${esc(String(catalogTime).slice(0,10))}；拍攝時間以影像內標示為準。</p>`,'LIVE CAMERAS');if($('cameraChoice'))$('cameraChoice').onchange=e=>showCamera(alternatives[Number(e.target.value)],alternatives,catalogTime);const reload=()=>{stopCamera();if(document.hidden||state.panel!=='camera')return;const seq=state.cameraSequence;const img=new Image();state.cameraImage=img;img.referrerPolicy='no-referrer';img.alt=c.name+' 公開影像';const url=new URL(c.image);const thumbnail=/i\.ytimg\.com/.test(url.hostname);const snapshot=/\.(jpg|jpeg|png)(\?|$)/i.test(url.href);if(snapshot)url.searchParams.set('_gd',Math.floor(Date.now()/60000));let slow=setTimeout(()=>{if(seq===state.cameraSequence&&$('cameraStatus'))$('cameraStatus').textContent='來源回應較慢，可按「在原站觀看」。'},12000);img.onload=()=>{clearTimeout(slow);if(seq!==state.cameraSequence||state.panel!=='camera')return;$('cameraLoading')?.remove();$('cameraStatus').textContent=thumbnail?'直播縮圖，請按「在原站觀看」播放影片。':`接收於 ${new Date().toLocaleTimeString('zh-TW')} · 拍攝時間以畫面為準。`;if(snapshot)state.cameraTimer=setTimeout(reload,60000)};img.onerror=()=>{clearTimeout(slow);if(seq!==state.cameraSequence||state.panel!=='camera')return;$('cameraLoading')?.remove();img.remove();$('cameraStatus').textContent='影像來源目前無法連線，請稍後重試或前往原站。'};$('cameraFrame').append(img);img.src=url.href};$('refreshCamera').onclick=reload;reload()}
function showQuake(q){state.selected={lat:q.lat,lng:q.lng,title:q.title||'地震位置'};const time=new Date(q.time).toLocaleString('zh-TW');openPanel('quake',q.title||'近期地震',`<div class="weather-summary"><div class="metric"><span class="label">規模</span><div class="value">${esc(q.mag)}</div></div><div class="metric"><span class="label">深度</span><div class="value">${fmt(q.depth)} <span>km</span></div></div></div><p class="subtle">${esc(time)}（手機時區）<br>${esc(q.place||'')}<br>${coords(q)}</p><p class="micro">來源：USGS。此為地震紀錄，不是即時預警。</p>${typeof q.url==='string'&&q.url.startsWith('https://earthquake.usgs.gov/')?sourceLink(q.url,'查看 USGS 地震詳情'):''}<div class="actions"><button class="button" data-action="save-selected">收藏位置</button><button class="button" data-action="share-selected">分享位置</button></div>`,'EARTHQUAKE')}
const poiTypes=[['hospital','✚','醫院'],['pharmacy','＋','藥局'],['police','◇','警察'],['fire_station','♨','消防'],['gas_station','▣','加油站'],['parking','P','停車場'],['toilet','↔','廁所'],['charging','ϟ','充電站'],['embassy','⚑','使領館']];
function renderParking(scope='viewport'){if(!mapReady())return;clearPoi();parkingController??=createParkingUI({map:()=>state.map,openPanel,closePanel,isOpen:()=>state.panel==='parking',routeTo:lot=>{journey=parkingHandoff(journeyForSelection(journey,state.selected)?.destination||state.selected,lot);write('geodeck.journey',journey);state.selected=journey.parking;renderRoutes()}});if(scope==='destination')parkingController.enable(state.selected);else parkingController.toggle()}
function renderField(scope='gps'){poiScope=scope;openPanel('field','附近設施',`<label class="form-field">搜尋中心<select id="poiScope"><option value="gps">我附近（目前 GPS 位置）</option>${state.selected?'<option value="selected">此位置附近</option>':''}<option value="map">地圖中心附近</option></select></label><p class="micro">半徑 6 km；定位失敗不會偷偷改用其他位置。</p><div class="poi-grid">${poiTypes.map(([id,icon,title])=>`<button data-poi="${id}"><span aria-hidden="true">${icon}</span>${title}</button>`).join('')}</div><div id="poiResults" class="poi-list"></div><button class="text-button" data-action="clear-poi">清除設施標記</button><p class="micro">OpenStreetMap / Photon · 收錄可能不完整，營業與服務以現場及官方資訊為準。</p>`,'FIELD MODE');$('poiScope').value=scope;$('poiScope').onchange=()=>{poiScope=$('poiScope').value;poiSequence++;clearPoi();$('poiResults').textContent='請選擇設施類型。'}}
function clearPoi(){state.poiMarkers.forEach(m=>m.setMap(null));state.poiMarkers=[]}
async function loadPoi(type){if(!mapReady())return;const token=++poiSequence;clearPoi();$('poiResults').innerHTML=loading(poiScope==='gps'?'取得目前位置…':'搜尋附近設施…');try{
const center=poiScope==='gps'?await getPosition():poiScope==='selected'?state.selected:{lat:state.map.getCenter().lat(),lng:state.map.getCenter().lng()};
if(token!==poiSequence||state.panel!=='field')return;
const points=await nearbyPlaces(type,center);if(token!==poiSequence||state.panel!=='field')return;
if(!points.length){$('poiResults').textContent='此位置半徑 6 km 沒有已收錄結果；不代表附近沒有設施，可切換搜尋中心。';return}
points.forEach((p,i)=>{const marker=createMarker({map:state.map,position:p,title:p.title,label:{text:String(i+1),color:'#fff',fontSize:'12px'}});marker.addListener('click',()=>selectLocation(p));state.poiMarkers.push(marker)});
$('poiResults').innerHTML=points.map((p,i)=>`<button data-poi-result="${i}">${i+1}. ${esc(p.title)}</button>`).join('');$('poiResults').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>selectLocation(points[i],{pan:true}));state.map.panTo(center);state.map.setZoom(13);
}catch(error){if(token===poiSequence&&state.panel==='field')$('poiResults').innerHTML=`<p class="warning">${esc(error.code===1?'未允許定位，請允許定位或選擇「此位置附近／地圖中心附近」。':error.code===2||error.code===3?'無法取得目前位置，請重試或切換搜尋中心。':error.message)}</p>`}}

function renderSettings(){openPanel('settings','設定與關於',`<h2>GeoDeck 出行助手</h2><p class="subtle">查看附近環境、找停車位，前往時交給導航 App。</p><h2>加入主畫面</h2><p class="subtle">iPhone：Safari 分享 → 加入主畫面。Android：在瀏覽器選單選擇安裝或加入主畫面。</p><h2>資料與隱私</h2><p class="micro">收藏、車位與備註儲存在這台裝置。搜尋與天氣查詢會將相關文字、座標送給資料服務。網頁不會在背景追蹤位置。</p><p class="micro">底圖：${sourceLink('https://maps.google.com/','Google Maps')}<br>搜尋：${sourceLink('https://github.com/komoot/photon','Photon')}／OpenStreetMap<br>天氣／AQI：${sourceLink('https://open-meteo.com/','Open-Meteo')}／CAMS<br>雷達：RainViewer · 雲圖：NASA GIBS<br>影像：twipcam · 地震：USGS</p><p class="micro">Google 底圖使用專案共用額度，超過免費用量可能計費。公開停車與天氣服務有免費用量限制。導航路線與班次由所選 App 提供。</p><p class="micro">GeoDeck ${VERSION}</p><button class="button full" data-action="check-update">檢查更新</button>`,'PREFERENCES')}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('裝置不支援定位'));navigator.geolocation.getCurrentPosition(p=>{const point={lat:p.coords.latitude,lng:p.coords.longitude,title:'目前位置'};state.userPoint=point;if(state.map){locationMarker??=createMarker({map:state.map,position:point,title:'目前位置',icon:{scale:9,fillColor:'#88b3db'}});locationMarker.setPosition(point)}resolve(point)},reject,{enableHighAccuracy:true,maximumAge:10000,timeout:12000})})}
async function locate(){if(!mapReady())return;$('locate').disabled=true;try{const p=await getPosition();state.map.panTo(p);state.map.setZoom(15)}catch{toast('無法取得定位，可檢查定位權限或直接選取地圖')}finally{$('locate').disabled=false}}
function rememberCar(p){parkedCar={...p,title:'我的停車位置',savedAt:new Date().toISOString()};if(write('geodeck.parked',parkedCar)){toast('已記住停車位置');renderFavorites()}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera()});
$('layers').onclick=()=>state.panel==='layers'?closePanel():renderLayers();$('routes').onclick=()=>state.panel==='routes'?closePanel():renderRoutes();$('favorites').onclick=()=>state.panel==='favorites'?closePanel():renderFavorites();$('field').onclick=()=>renderField();$('settings').onclick=renderSettings;$('closePanel').onclick=closePanel;$('locate').onclick=locate;
$('centerWeather').onclick=()=>{if(!mapReady())return;const c=state.map.getCenter();selectLocation({lat:c.lat(),lng:c.lng(),title:'地圖中心'})};
$('radarPlay').onclick=()=>state.layers?.radarPlay();$('radarLatest').onclick=()=>state.layers?.radarLatest();$('radarRange').oninput=e=>{state.layers?.pauseRadar();state.layers?.radarAt(Number(e.target.value))};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel()});
$('searchForm').onsubmit=async e=>{e.preventDefault();const text=$('search').value.trim();if(!text)return;openPanel('search','搜尋地點',loading('搜尋中…'),'PLACES');const token=++searchSequence;const external='https://www.google.com/maps/search/?'+new URLSearchParams({api:'1',query:text});
const fallback=`<p class="micro">OpenStreetMap / Photon · 收錄可能不完整</p><a class="button full" href="${esc(external)}" target="_blank" rel="noopener noreferrer">在 Google Maps 搜尋此文字 ↗</a>`;
try{const c=state.map?.getCenter(),rows=await placeSearch.search(text,{known:state.saved,center:c?{lat:c.lat(),lng:c.lng()}:null});if(token!==searchSequence||state.panel!=='search')return;
if(rows.length===1&&parseCoordinates(text)){$('search').blur();selectLocation(rows[0],{pan:true});return}
$('panelBody').innerHTML=(rows.length?'<div class="poi-list">'+rows.map((p,i)=>`<button data-search-result="${i}"><b>${esc(p.title)}</b><small>${esc(p.address||coords(p))}</small></button>`).join('')+'</div>':'<p class="subtle">查無相符地點，可補上城市名稱或在地圖選點。</p>')+fallback;
$('panelBody').querySelectorAll('[data-search-result]').forEach(b=>b.onclick=()=>{selectLocation(rows[Number(b.dataset.searchResult)],{pan:true});$('search').blur()});
}catch(error){if(token===searchSequence&&state.panel==='search')$('panelBody').innerHTML=`<p class="warning">${esc(error.message)}</p>`+fallback}};
$('panelBody').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
if(d.layer){if(!mapReady())return;const on=!state.layers.enabled.has(d.layer);b.setAttribute('aria-pressed',String(on));state.layers.set(d.layer,on);write('geodeck.layers',[...state.layers.enabled])}
if(d.savedOpen!==undefined)selectLocation(state.saved[Number(d.savedOpen)],{pan:true});
if(d.savedEdit!==undefined)editSaved(state.saved[Number(d.savedEdit)]);
if(d.savedRoute!==undefined){state.selected=state.saved[Number(d.savedRoute)];renderRoutes()}
if(d.savedDelete!==undefined){const next=state.saved.filter((_,i)=>i!==Number(d.savedDelete));if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已移除收藏')}}
if(d.poi)loadPoi(d.poi);
switch(d.action){case'route-selected':renderRoutes();break;case'save-selected':if(state.selected)editSaved(state.selected);break;case'share-selected':shareSelected();break;
case'nearby-parking':renderParking('destination');break;
case'nearby-cameras':if(!mapReady())break;closePanel();state.map.panTo(state.selected);state.map.setZoom(14);state.layers.set('camera',true);write('geodeck.layers',[...state.layers.enabled]);break;
case'nearby-facilities':renderField('selected');break;case'export-favorites':exportFavorites();break;
case'clear-poi':poiSequence++;clearPoi();if($('poiResults'))$('poiResults').innerHTML='';break;
case'check-update':checkUpdate();break;
case'car-open':if(parkedCar)selectLocation(parkedCar,{pan:true});break;
case'car-route':if(parkedCar)navigationController.walkTo(parkedCar);break;
case'car-clear':if(write('geodeck.parked',null)){parkedCar=null;renderFavorites()}break;
case'car-save':b.disabled=true;try{rememberCar(await getPosition())}catch{toast('無法定位，請在地圖選取停車位置後收藏')}finally{b.disabled=false}break;
}});
navigationController=createNavigationUI({openPanel,isOpen:()=>state.panel==='routes',selected:()=>state.selected,setSelected:p=>state.selected=p,saved:()=>state.saved,
search:(q,opts)=>placeSearch.search(q,opts),country:p=>placeSearch.country(p),center:()=>{const p=state.map?.getCenter();return p?{lat:p.lat(),lng:p.lng()}:null},read,write,findParking:()=>renderParking('destination'),journey:()=>journeyForSelection(journey,state.selected),parked:rememberCar});
async function loadMap(){try{
if(!navigator.onLine){mapFailure('目前離線，連線後可重新載入地圖。收藏與備註仍可使用。');return}
state.map=await createMap($('map'),{center:{lat:22.9915,lng:120.204},zoom:13});$('mapState').classList.add('hidden');
state.layers=createLayers(state.map,{status:updateLayerStatus,camera:showCamera,point:selectLocation,quake:showQuake,radarState:renderRadar});
state.map.addListener('click',e=>selectLocation({lat:e.latLng.lat(),lng:e.latLng.lng(),title:'選取位置'}));
const stored=read('geodeck.layers',[]);if(Array.isArray(stored))for(const id of stored.filter(x=>Object.hasOwn(state.layers.names,x)))state.layers.set(id,true);
const params=new URL(location.href).searchParams,p={lat:Number(params.get('lat')),lng:Number(params.get('lng')),title:params.get('name')?.slice(0,120)||'分享的位置'};
if(params.has('lat')&&params.has('lng')&&validPoint(p))selectLocation(p,{pan:true});
}catch(e){mapFailure(e.message||'地圖暫時無法連線，收藏仍可使用。')}}
function networkState(){$('offlineBanner').classList.toggle('hidden',navigator.onLine)}window.addEventListener('online',networkState);window.addEventListener('offline',networkState);networkState();
let swRegistration,updateRequested=false;
async function checkUpdate(){if(!swRegistration){toast('請重新開啟網址以取得最新版');return}await swRegistration.update();if(swRegistration.waiting){$('updateBanner').classList.remove('hidden')}else toast('已檢查更新，目前版本 '+VERSION)}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(r=>{swRegistration=r;if(r.waiting)$('updateBanner').classList.remove('hidden');r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('updateBanner').classList.remove('hidden')})});r.update().catch(()=>{})}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updateRequested)location.reload()})}
$('applyUpdate').onclick=()=>{if(swRegistration?.waiting){updateRequested=true;swRegistration.waiting.postMessage({type:'SKIP_WAITING'})}else location.reload()};
loadMap();
