import {createParkingUI} from './parking-ui.js?v=0.4.0';
import {computeModernRoute,createModernRenderer} from './routes-provider.js?v=0.4.0';
import {createDrive} from './drive.js?v=0.4.0';
import {VERSION,finite,escapeHtml as esc,validPoint,parseCoordinates,weatherInfo,aqiInfo,gpsSpeed,navigationUrl,regionalProvider,normalizedSaved} from './core.js?v=0.4.0';
import {createLayers,jsonFetch} from './layers.js?v=0.4.0';
const $=id=>document.getElementById(id),fmt=(v,suffix='')=>finite(v)?Math.round(v)+suffix:'—';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('此瀏覽器無法儲存資料，請確認儲存空間');return false}};
const state={map:null,layers:null,panel:'',selected:null,selection:0,placeAbort:null,userPoint:null,saved:normalizedSaved(read('geodeck.saved',[])),settings:{speed:false,limit:null,enforcementDistance:500,vibrate:true,buffer:0,voice:true,awake:true,...read('geodeck.settings',{})},layerStatuses:new Map(),route:null,routeMode:'driving',provider:'auto',routeSequence:0,routeOrigin:null,cameraTimer:null,cameraImage:null,cameraSequence:0,poiMarkers:[]};
let parkingController;
$('parking').onclick=()=>renderParking();
let driveController,suspendedLayers=[],legacyDirectionsDenied=false;
let toastTimer,selectionMarker,locationMarker,accuracyCircle,geocoder,placesService,routeRenderer,watchId=null,lastGps=null,lastGpsAt=0,lastAlert=0,wakeLock=null,audioContext=null;
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4200)}
function stopCamera(){state.cameraSequence++;clearTimeout(state.cameraTimer);if(state.cameraImage){state.cameraImage.src='';state.cameraImage.remove();state.cameraImage=null}}
function openPanel(kind,title,html,eyebrow='GEODECK'){if(state.panel==='camera')stopCamera();state.panel=kind;$('panel').dataset.kind=kind;$('panelEyebrow').textContent=eyebrow;$('panelTitle').textContent=title;$('panelBody').innerHTML=html;$('panel').classList.remove('hidden');document.body.classList.add('panel-open');for(const id of ['layers','routes','favorites'])$(id).setAttribute('aria-expanded',String(kind===id));$('panelBody').scrollTop=0}
function closePanel(){if(state.panel==='routes')state.routeSequence++;if(state.panel==='camera')stopCamera();state.panel='';$('panel').classList.add('hidden');document.body.classList.remove('panel-open');for(const id of ['layers','routes','favorites'])$(id).setAttribute('aria-expanded','false')}
function loading(text='載入中…'){return `<p class="subtle" role="status">${esc(text)}</p>`}
function sourceLink(url,title){return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`}
function mapReady(){if(state.map)return true;toast(navigator.onLine?'地圖尚未載入，請稍候或重新開啟':'目前離線，仍可查看收藏與備註');return false}
function mapFailure(message){$('mapState').classList.remove('hidden');$('mapState').innerHTML=`<strong>地圖暫時無法開啟</strong><p>${esc(message)}</p><button class="button" id="retryMap">重新載入</button>`;$('retryMap').onclick=()=>location.reload()}
function renderLayers(){const on=state.layers?.enabled||new Set(),base=state.map?.getMapTypeId()||'roadmap';const items=[['radar','☂','雷達回波','過去 2 小時，可播放'],['cloud','☁','衛星雲圖','依地區選擇衛星'],['camera','▣','即時影像','台灣公開道路與景點'],['aqi','≋','空氣品質','美國 AQI · 模式格點'],['traffic','↝','即時路況','Google 交通資訊'],['earthquake','◉','近期地震','USGS · 過去 7 天']];openPanel('layers','資訊圖層',`<h2>底圖</h2><div class="segmented" aria-label="選擇底圖">${[['roadmap','深色地圖'],['hybrid','衛星'],['terrain','地形']].map(([id,t])=>`<button data-base="${id}" aria-pressed="${base===id}">${t}</button>`).join('')}</div><div class="layer-grid">${items.map(([id,icon,title,note])=>`<button class="layer-card" data-layer="${id}" aria-pressed="${on.has(id)}"><span class="symbol" aria-hidden="true">${icon}</span><b>${title}</b><small>${note}</small></button>`).join('')}</div><div id="layerDetails">${layerDetails()}</div><p class="micro">衛星雲圖在亞太、美洲使用紅外線影像；其他地區使用全球日雲圖。影像留白可能是來源未涵蓋。</p><p class="micro">地震紀錄供查詢，沒有即時預警功能。</p>`,'MAP LAYERS')}
function layerDetails(){return [...state.layerStatuses].filter(([id])=>state.layers?.enabled.has(id)).map(([id,s])=>`<p class="micro">${esc(s)}</p>`).join('')}
function updateLayerStatus(id,message,on){if(on)state.layerStatuses.set(id,message);else state.layerStatuses.delete(id);$('layerBadges').innerHTML=[...state.layerStatuses].map(([id,s])=>`<span>${esc(s)}</span>`).join('');const count=state.layers?.enabled.size||0;$('layerCount').textContent=count;$('layerCount').classList.toggle('hidden',!count);if(state.panel==='layers'&&$('layerDetails'))$('layerDetails').innerHTML=layerDetails()}
function renderRadar(data){$('radarControl').classList.toggle('hidden',!data);if(!data)return;$('radarRange').max=data.frames.length-1;$('radarRange').value=data.index;$('radarPlay').textContent=data.playing?'Ⅱ':'▶';$('radarPlay').setAttribute('aria-label',data.playing?'暫停雷達':'播放雷達');const t=data.frames[data.index].time*1000;$('radarTime').textContent=new Date(t).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})+' · 雷達回波';$('radarSource').textContent='RainViewer · 合成時間（手機時區）'}
function coords(p){return p.lat.toFixed(5)+', '+p.lng.toFixed(5)}
function isSaved(p){return state.saved.some(s=>Math.abs(s.lat-p.lat)<.00001&&Math.abs(s.lng-p.lng)<.00001)}
async function selectLocation(p,{pan=false}={}){if(!validPoint(p))return;state.selected={...p,title:p.title||'選取位置'};const token=++state.selection;state.placeAbort?.abort();state.placeAbort=new AbortController();if(state.map){selectionMarker?.setMap(null);selectionMarker=new google.maps.Marker({map:state.map,position:p,title:state.selected.title,icon:{path:google.maps.SymbolPath.CIRCLE,scale:9,fillColor:'#d8f7a5',fillOpacity:1,strokeColor:'#17291b',strokeWeight:3},zIndex:100});if(pan){state.map.panTo(p);state.map.setZoom(Math.max(14,state.map.getZoom()))}}
openPanel('place',state.selected.title,`<p class="location-meta" id="placeCoords">${coords(p)}</p><div class="actions"><button class="button primary" data-action="route-selected">↗ 前往這裡</button><button class="button" data-action="save-selected">${isSaved(p)?'✓ 已收藏':'☆ 收藏'}</button><button class="button" data-action="share-selected">分享</button></div><div id="weatherContent">${loading('讀取逐時天氣…')}</div><div id="aqiContent">${loading('讀取空氣品質…')}</div><div class="actions"><button class="button" data-action="nearby-cameras">附近影像</button><button class="button" data-action="nearby-facilities">附近設施</button></div>`,'LOCATION');
const still=()=>token===state.selection&&state.panel==='place';
loadWeather(p,state.placeAbort.signal).then(d=>{if(still())renderWeather(d)}).catch(e=>{if(still()&&e.name!=='AbortError')$('weatherContent').innerHTML='<p class="error">天氣暫時無法取得，請稍後重新點選位置。</p>'});
loadAqi(p,state.placeAbort.signal).then(d=>{if(still())renderAqi(d)}).catch(e=>{if(still()&&e.name!=='AbortError')$('aqiContent').innerHTML='<p class="error">空氣品質暫時無法取得。</p>'});
if(geocoder&&!p.country){geocoder.geocode({location:p},(r,s)=>{if(token!==state.selection||s!=='OK'||!r?.length)return;const country=r[0].address_components.find(x=>x.types.includes('country'))?.short_name;state.selected.country=country||'';if(state.selected.title==='選取位置')state.selected.title=r[0].formatted_address;if(still()){$('panelTitle').textContent=state.selected.title;$('placeCoords').textContent=coords(p)+(country?' · '+country:'')}})}}
const weatherCache=new Map();
async function loadWeather(p,signal){const key=p.lat.toFixed(3)+','+p.lng.toFixed(3);const cache=weatherCache.get(key);if(cache&&Date.now()-cache.at<600000)return cache.data;const q=new URLSearchParams({latitude:p.lat,longitude:p.lng,current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'sunrise,sunset,uv_index_max',forecast_days:'2',timezone:'auto',timeformat:'unixtime'});const d=await jsonFetch('https://api.open-meteo.com/v1/forecast?'+q,16000,signal);weatherCache.set(key,{at:Date.now(),data:d});if(weatherCache.size>25)weatherCache.delete(weatherCache.keys().next().value);return d}
async function loadAqi(p,signal){const q=new URLSearchParams({latitude:p.lat,longitude:p.lng,current:'us_aqi,pm2_5,pm10',timezone:'auto',timeformat:'unixtime'});return jsonFetch('https://air-quality-api.open-meteo.com/v1/air-quality?'+q,16000,signal)}
function localTime(timestamp,zone,withDate=false){if(!finite(timestamp))return'—';try{return new Intl.DateTimeFormat('zh-TW',{timeZone:zone||'UTC',hour:'2-digit',minute:'2-digit',hourCycle:'h23',...(withDate?{month:'numeric',day:'numeric'}:{})}).format(new Date(timestamp*1000))}catch{return new Date(timestamp*1000).toISOString().slice(11,16)+' UTC'}}
function renderWeather(d){const c=d.current||{},[label,icon]=weatherInfo(c.weather_code),h=d.hourly||{},daily=d.daily||{};let hours='';for(let i=0,n=0;i<(h.time||[]).length&&n<24;i++){if(h.time[i]<Math.floor(Date.now()/3600000)*3600)continue;const [text,symbol]=weatherInfo(h.weather_code[i]);hours+=`<div class="hour"><small>${localTime(h.time[i],d.timezone)}</small><span class="weather-icon" aria-label="${text}">${symbol}</span><b>${fmt(h.temperature_2m[i],'°')}</b><span class="rain">${fmt(h.precipitation_probability?.[i],'%')}</span></div>`;n++}
$('weatherContent').innerHTML=`<div class="weather-summary"><div class="metric"><span class="label">${icon} ${label}</span><div class="value">${fmt(c.temperature_2m,'°')} <span>C</span></div><div class="detail">體感 ${fmt(c.apparent_temperature,'°')} · 濕度 ${fmt(c.relative_humidity_2m,'%')}</div></div><div class="metric"><span class="label">風速／風向</span><div class="value">${fmt(c.wind_speed_10m)} <span>km/h</span></div><div class="detail">${windDirection(c.wind_direction_10m)} · ${fmt(c.wind_direction_10m,'°')}</div></div></div><h2>未來 24 小時 <span class="subtle">· ${esc(d.timezone||'UTC')} 當地時間</span></h2><div class="hourly" aria-label="逐時氣溫與降雨機率">${hours||'<p class="subtle">暫無逐時資料</p>'}</div><p class="micro">百分比為各時段降雨機率。</p><div class="weather-more"><div><span>日出／日落</span>${localTime(daily.sunrise?.[0],d.timezone)} / ${localTime(daily.sunset?.[0],d.timezone)}</div><div><span>今日最高紫外線指數</span>${fmt(daily.uv_index_max?.[0])}</div></div><p class="micro forecast-note">${sourceLink('https://open-meteo.com/','Open-Meteo')} · 數值模式預報<br>資料時刻：${localTime(c.time,d.timezone,true)}（當地時間）${Date.now()-c.time*1000>7200000?' · 資料較舊':''}</p>`;
$('centerLabel').textContent=`${fmt(c.temperature_2m,'°')} ${label} · 已選位置`}
function windDirection(v){return finite(v)?['北','東北','東','東南','南','西南','西','西北'][Math.round(v/45)%8]+'風':'—'}
function renderAqi(d){const c=d.current||{},info=aqiInfo(c.us_aqi);$('aqiContent').innerHTML=`<h2>空氣品質</h2><div class="metric aqi" style="--aqi:${info.color}"><div class="row"><div><div class="label">美國 AQI · ${info.label}</div><div class="value">${fmt(c.us_aqi)}</div></div><div class="detail">PM2.5 ${fmt(c.pm2_5)} µg/m³<br>PM10 ${fmt(c.pm10)} µg/m³</div></div></div><p class="micro">${sourceLink('https://open-meteo.com/en/docs/air-quality-api','Open-Meteo／CAMS')} · 模式估計，非現地測站<br>資料時刻：${localTime(c.time,d.timezone,true)}（當地時間）${Date.now()-c.time*1000>10800000?' · 資料較舊':''}</p>`}
function renderFavorites(){openPanel('favorites','我的收藏',`<p class="subtle">儲存在這台裝置。離線也能查看地點與備註。</p>${state.saved.length?state.saved.map((p,i)=>`<article class="saved-item"><button class="saved-open" data-saved-open="${i}">${esc(p.title)}</button><p>${coords(p)}${p.note?'\n'+esc(p.note):''}</p><div class="saved-actions"><button class="text-button" data-saved-edit="${i}">編輯</button><button class="text-button" data-saved-route="${i}">前往</button><button class="text-button" data-saved-delete="${i}">移除</button></div></article>`).join(''):'<div class="empty"><strong>把想去的地方留在這裡</strong>搜尋或點選地圖上的位置，按「收藏」。</div>'}<div class="actions"><button class="button" data-action="export-favorites">匯出備份</button><label class="button">匯入備份<input id="importFavorites" type="file" accept="application/json,.json" hidden></label></div>`,'SAVED PLACES');$('importFavorites').onchange=importFavorites}
function editSaved(p){const existing=state.saved.find(s=>Math.abs(s.lat-p.lat)<.00001&&Math.abs(s.lng-p.lng)<.00001);openPanel('edit','收藏地點',`<form id="savedForm"><label class="form-field">名稱<input id="savedName" maxlength="120" required value="${esc(existing?.title||p.title)}"></label><p class="subtle">${coords(p)}</p><label class="form-field">備註<textarea id="savedNote" maxlength="4000" placeholder="例如：集合位置、出口、開放時間">${esc(existing?.note||'')}</textarea></label><button class="button primary full" type="submit">儲存收藏</button></form>`,'SAVED PLACES');$('savedForm').onsubmit=e=>{e.preventDefault();const item={...p,id:existing?.id||coords(p),title:$('savedName').value.trim()||'收藏地點',note:$('savedNote').value.trim(),savedAt:existing?.savedAt||new Date().toISOString()};const next=[item,...state.saved.filter(s=>s!==existing)].slice(0,200);if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已儲存收藏')}}}
function exportFavorites(){const blob=new Blob([JSON.stringify({app:'GeoDeck',version:VERSION,exportedAt:new Date().toISOString(),places:state.saved},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='geodeck-favorites.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importFavorites(e){const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024)return toast('備份檔案太大');try{const d=JSON.parse(await file.text()),raw=Array.isArray(d)?d:d.places;if(!Array.isArray(raw)||!raw.every(validPoint))throw Error();const next=normalizedSaved([...state.saved,...raw]);if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已合併收藏，重複座標保留原有備註')}}catch{toast('無法讀取這個收藏備份')}}
async function shareSelected(){const p=state.selected;if(!p)return;const u=new URL('./',location.href);u.searchParams.set('lat',p.lat.toFixed(6));u.searchParams.set('lng',p.lng.toFixed(6));u.searchParams.set('name',p.title.slice(0,120));try{if(navigator.share)await navigator.share({title:p.title,url:u.href});else{await navigator.clipboard.writeText(u.href);toast('地點連結已複製')}}catch(e){if(e.name!=='AbortError')toast('分享未完成，可在收藏中保留座標')}}
function renderRoutes(){state.routeSequence++;const p=state.selected;openPanel('routes','路線規劃',`<form id="routeForm"><label class="form-field">出發地<input id="routeOrigin" placeholder="目前位置，或輸入出發地" value="${esc(state.routeOrigin?.title||'')}"></label><label class="form-field">目的地<input id="routeDestination" placeholder="搜尋地點或輸入座標" required value="${esc(p?.title||'')}"></label><div class="segmented" aria-label="交通方式">${[['driving','開車'],['walking','步行'],['transit','大眾運輸']].map(([id,t])=>`<button type="button" data-travel="${id}" aria-pressed="${state.routeMode===id}">${t}</button>`).join('')}</div><label class="form-field">導航服務<select id="routeProvider"><option value="auto">依目的地自動選擇</option value="google">Google Maps</option><option value="naver">NAVER Maps（韓國，需安裝）</option><option value="amap">高德地圖（中國大陸）</option></select></label><button id="routeSubmit" class="button primary full" type="submit">查看路線</button></form><div id="routeResult"></div><div id="externalRoute"></div><button type="button" class="button full" data-action="free-drive">自由駕駛 · 測速提醒</button><p class="micro">Drive Mode 需保持前景、螢幕開啟；無路線時不提供轉向。車道資料未提供，顯示 unavailable。</p><p class="micro">路線與班次依當地資料涵蓋。開啟其他導航 App 後，本網頁的 GPS 提醒會暫停。</p>${state.route?'<button class="text-button" data-action="clear-route">清除地圖上的路線</button>':''}`,'DIRECTIONS');$('routeProvider').value=state.provider;$('routeProvider').onchange=()=>{state.provider=$('routeProvider').value;renderExternalRoute()};$('routeForm').onsubmit=calculateRoute;renderExternalRoute()}
function renderExternalRoute(){if(state.panel!=='routes'||!state.selected||!$('externalRoute'))return;const provider=state.provider==='auto'?regionalProvider(state.selected,state.selected.country):state.provider;const title={google:'Google Maps',naver:'NAVER Maps',amap:'高德地圖'}[provider];const href=navigationUrl({destination:state.selected,origin:state.routeOrigin,mode:state.routeMode,provider});$('externalRoute').innerHTML=`<a id="openNavigation" class="button full" style="margin-top:12px" href="${esc(href)}" ${provider==='naver'?'':'target="_blank" rel="noopener noreferrer"'}>在 ${title} 開啟${state.routeMode==='transit'?'大眾運輸':'導航'} ↗</a>${provider==='naver'?'<p class="micro">需要已安裝 NAVER Maps；未安裝時可改選 Google Maps。</p>':''}`}
async function resolveLocation(text){const p=parseCoordinates(text);if(p)return{...p,title:text};if(!geocoder)throw Error('地圖尚未載入');return new Promise((resolve,reject)=>geocoder.geocode({address:text},(r,status)=>{if(status!=='OK'||!r?.length)return reject(Error('找不到這個地點'));const x=r[0];resolve({lat:x.geometry.location.lat(),lng:x.geometry.location.lng(),title:x.formatted_address,placeId:x.place_id,country:x.address_components.find(c=>c.types.includes('country'))?.short_name||''})}))}
async function calculateRoute(e){e.preventDefault();if(!mapReady())return;const token=++state.routeSequence,originText=$('routeOrigin').value.trim(),destText=$('routeDestination').value.trim();$('routeSubmit').disabled=true;$('routeResult').innerHTML=loading('正在查詢路線…');try{const [origin,destination]=await Promise.all([originText?resolveLocation(originText):getPosition(),state.selected&&destText===state.selected.title?Promise.resolve(state.selected):resolveLocation(destText)]);if(token!==state.routeSequence||state.panel!=='routes')return;state.routeOrigin={...origin,title:origin.title||'目前位置'};state.selected=destination;renderExternalRoute();const provider=state.provider==='auto'?regionalProvider(destination,destination.country):state.provider;if(provider!=='google'){$('routeResult').innerHTML='<p class="subtle">目的地已備妥。請按下方按鈕，在當地導航服務查看完整路線與班次。</p>';return}
const mode={driving:google.maps.TravelMode.DRIVING,walking:google.maps.TravelMode.WALKING,transit:google.maps.TravelMode.TRANSIT}[state.routeMode],request={origin:{lat:origin.lat,lng:origin.lng},destination:{lat:destination.lat,lng:destination.lng},travelMode:mode,provideRouteAlternatives:true};if(mode===google.maps.TravelMode.TRANSIT)request.transitOptions={departureTime:new Date()};if(mode===google.maps.TravelMode.DRIVING)request.drivingOptions={departureTime:new Date()};let result;try{if(legacyDirectionsDenied&&state.routeMode==='driving')throw Error('REQUEST_DENIED');result=await new Promise((resolve,reject)=>new google.maps.DirectionsService().route(request,(r,status)=>status==='OK'&&r?resolve(r):reject(Error(status))))}catch(error){if(error.message!=='REQUEST_DENIED'||state.routeMode!=='driving')throw error;legacyDirectionsDenied=true;result=await computeModernRoute(request.origin,request.destination)}if(token!==state.routeSequence||state.panel!=='routes')return;state.route=result;routeRenderer?.setMap(null);routeRenderer=result.routes?.[0]?.modern?createModernRenderer(state.map):new google.maps.DirectionsRenderer({map:state.map,suppressMarkers:false,polylineOptions:{strokeColor:'#a9bfd3',strokeWeight:6,strokeOpacity:.95}});routeRenderer.setMap(state.map);routeRenderer.setDirections(result);showRouteResult(0)
}catch(err){console.warn('GeoDeck route request failed:',String(err.message||err).slice(0,300));if(token===state.routeSequence&&state.panel==='routes'){$('routeResult').innerHTML=`<p class="warning">${esc(err.message==='找不到這個地點'?err.message:err.code===1?'請輸入出發地，或允許瀏覽器定位。':'圖內路線目前不可用。可使用下方 Google Maps 開啟導航，或選「自由駕駛」測試執法提醒（不含轉向指引）。')}</p>`;renderExternalRoute()}}finally{if(token===state.routeSequence&&state.panel==='routes'&&$('routeSubmit'))$('routeSubmit').disabled=false}}
function stripHtml(s){const d=new DOMParser().parseFromString(String(s||''),'text/html');return d.body.textContent||''}
function showRouteResult(index){state.routeIndex=index;if(!state.route||state.panel!=='routes')return;routeRenderer.setRouteIndex(index);const routes=state.route.routes;const r=routes[index],leg=r.legs[0];$('routeResult').innerHTML=`<div class="route-result">${routes.map((x,i)=>`<button class="route-choice ${i===index?'selected':''}" data-route-index="${i}"><b>${esc(x.legs[0].duration_in_traffic?.text||x.legs[0].duration?.text||'')}</b><small>${esc(x.summary||'大眾運輸路線')} · ${esc(x.legs[0].distance?.text||'')}</small></button>`).join('')}${state.routeMode==='driving'?'<button class="button primary full" data-action="start-drive">開始 Drive Mode</button>':''}<ol class="step-list">${leg.steps.map(s=>`<li>${esc(stripHtml(s.instructions))}${s.transit?`<small>${esc(s.transit.line?.short_name||s.transit.line?.name||'')} · ${esc(s.transit.departure_stop?.name||'')} → ${esc(s.transit.arrival_stop?.name||'')}<br>${esc(s.transit.departure_time?.text||'')} 出發 · ${esc(s.transit.arrival_time?.text||'')} 抵達</small>`:`<small>${esc(s.distance?.text||'')}</small>`}</li>`).join('')}</ol><p class="micro">${esc(r.copyrights||'Google Maps')}${r.warnings?.length?'<br>'+r.warnings.map(esc).join('<br>'):''}</p></div>`}
function showCamera(c,alternatives=[c],catalogTime=''){state.selected={lat:c.lat,lng:c.lng,title:c.name};openPanel('camera',c.name,`${alternatives.length>1?`<label class="form-field">同位置的影像<select id="cameraChoice">${alternatives.map((v,i)=>`<option value="${i}">${esc(v.name)}</option>`).join('')}</select></label>`:''}<div class="camera-frame" id="cameraFrame"><span class="camera-loading" id="cameraLoading">正在連接公開影像…</span></div><p class="micro" id="cameraStatus" role="status">來源連線中</p><div class="actions"><button class="button" data-action="route-selected">前往這裡</button><button class="button" id="refreshCamera">重新整理</button></div><a class="button full" href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">在原站觀看 ↗</a><p class="micro">目錄來源：${sourceLink('https://www.twipcam.com/','台灣即時影像 twipcam')}<br>目錄取得：${esc(String(catalogTime).slice(0,10))}；拍攝時間以影像內標示為準。</p>`,'LIVE CAMERAS');if($('cameraChoice'))$('cameraChoice').onchange=e=>showCamera(alternatives[Number(e.target.value)],alternatives,catalogTime);const reload=()=>{stopCamera();if(document.hidden||state.panel!=='camera')return;const seq=state.cameraSequence;const img=new Image();state.cameraImage=img;img.referrerPolicy='no-referrer';img.alt=c.name+' 公開影像';const url=new URL(c.image);const thumbnail=/i\.ytimg\.com/.test(url.hostname);const snapshot=/\.(jpg|jpeg|png)(\?|$)/i.test(url.href);if(snapshot)url.searchParams.set('_gd',Math.floor(Date.now()/60000));let slow=setTimeout(()=>{if(seq===state.cameraSequence&&$('cameraStatus'))$('cameraStatus').textContent='來源回應較慢，可按「在原站觀看」。'},12000);img.onload=()=>{clearTimeout(slow);if(seq!==state.cameraSequence||state.panel!=='camera')return;$('cameraLoading')?.remove();$('cameraStatus').textContent=thumbnail?'直播縮圖，請按「在原站觀看」播放影片。':`接收於 ${new Date().toLocaleTimeString('zh-TW')} · 拍攝時間以畫面為準。`;if(snapshot)state.cameraTimer=setTimeout(reload,60000)};img.onerror=()=>{clearTimeout(slow);if(seq!==state.cameraSequence||state.panel!=='camera')return;$('cameraLoading')?.remove();img.remove();$('cameraStatus').textContent='影像來源目前無法連線，請稍後重試或前往原站。'};$('cameraFrame').append(img);img.src=url.href};$('refreshCamera').onclick=reload;reload()}
function showQuake(q){state.selected={lat:q.lat,lng:q.lng,title:q.title||'地震位置'};const time=new Date(q.time).toLocaleString('zh-TW');openPanel('quake',q.title||'近期地震',`<div class="weather-summary"><div class="metric"><span class="label">規模</span><div class="value">${esc(q.mag)}</div></div><div class="metric"><span class="label">深度</span><div class="value">${fmt(q.depth)} <span>km</span></div></div></div><p class="subtle">${esc(time)}（手機時區）<br>${esc(q.place||'')}<br>${coords(q)}</p><p class="micro">來源：USGS。此為地震紀錄，不是即時預警。</p>${typeof q.url==='string'&&q.url.startsWith('https://earthquake.usgs.gov/')?sourceLink(q.url,'查看 USGS 地震詳情'):''}<div class="actions"><button class="button" data-action="save-selected">收藏位置</button><button class="button" data-action="share-selected">分享位置</button></div>`,'EARTHQUAKE')}
const poiTypes=[['hospital','✚','醫院'],['pharmacy','＋','藥局'],['police','◇','警察'],['fire_station','♨','消防'],['gas_station','▣','加油站'],['parking','P','停車場'],['toilet','↔','廁所'],['charging','ϟ','充電站'],['embassy','⚑','使領館']];
function renderParking(){if(!mapReady())return;clearPoi();parkingController??=createParkingUI({map:()=>state.map,openPanel,isOpen:()=>state.panel==='parking',selected:()=>state.selected,getPosition,routeTo:lot=>{state.selected=lot;renderRoutes()}});parkingController.search()}
function renderField(){openPanel('field','附近設施',`<p class="subtle">以${state.selected?'已選位置':'地圖中心'}為中心搜尋，結果顯示在地圖上。</p><div class="poi-grid">${poiTypes.map(([id,icon,title])=>`<button data-poi="${id}"><span aria-hidden="true">${icon}</span>${title}</button>`).join('')}</div><div id="poiResults" class="poi-list"></div><button class="text-button" data-action="clear-poi">清除設施標記</button><h2>位置資訊</h2><p class="location-meta">${state.selected?coords(state.selected):state.map?coords({lat:state.map.getCenter().lat(),lng:state.map.getCenter().lng()}):'地圖尚未載入'}</p><p class="micro">公開地點資料可能有延遲；營業時間與服務請以現場及官方資訊為準。</p>`,'FIELD MODE')}
function clearPoi(){state.poiMarkers.forEach(m=>m.setMap(null));state.poiMarkers=[]}
function loadPoi(type){if(!mapReady())return;clearPoi();$('poiResults').innerHTML=loading('搜尋附近設施…');const center=state.selected||{lat:state.map.getCenter().lat(),lng:state.map.getCenter().lng()},keyword={toilet:'public toilet 公共廁所',charging:'electric vehicle charging station',embassy:'embassy consulate representative office'}[type];const request={location:center,radius:6000,...(keyword?{keyword}:{type})};if(!placesService){$('poiResults').innerHTML='<p class="warning">附近搜尋暫時無法使用。</p>';return}placesService.nearbySearch(request,(results,status)=>{if(state.panel!=='field')return;if(status!=='OK'||!results?.length){$('poiResults').innerHTML='<p class="subtle">此範圍暫無可用結果，可移動地圖後重試。</p>';return}const points=results.slice(0,15).map(p=>({lat:p.geometry.location.lat(),lng:p.geometry.location.lng(),title:p.name,placeId:p.place_id}));points.forEach((p,i)=>{const marker=new google.maps.Marker({map:state.map,position:p,title:p.title,label:{text:String(i+1),color:'#fff',fontSize:'12px'}});marker.addListener('click',()=>selectLocation(p));state.poiMarkers.push(marker)});$('poiResults').innerHTML=points.map((p,i)=>`<button data-poi-result="${i}">${i+1}. ${esc(p.title)}</button>`).join('');$('poiResults').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>selectLocation(points[i],{pan:true}));state.map.panTo(center);state.map.setZoom(13)})}
function renderSettings(){openPanel('settings','設定',`<h2>速度提醒</h2><form id="settingsForm"><label class="switch-row"><span>顯示 GPS 速度</span><input id="speedToggle" type="checkbox" ${state.settings.speed?'checked':''}></label><label class="form-field">自訂速度提醒門檻（km/h）<input id="speedLimit" type="number" inputmode="numeric" min="5" max="200" step="1" placeholder="不提醒則留白" value="${finite(state.settings.limit)?state.settings.limit:''}"></label><label class="switch-row"><span>提示音與語音</span><input id="voiceToggle" type="checkbox" ${state.settings.voice?'checked':''}></label><label class="switch-row"><span>顯示速度時保持螢幕開啟</span><input id="awakeToggle" type="checkbox" ${state.settings.awake?'checked':''}></label><p class="micro">提醒依你設定的門檻，並非道路速限。GPS 精度不足時不顯示速度；切換 App 或鎖屏後無法持續提醒。Drive Mode 已接入官方執法快照。執法點速限不等於目前道路速限，請依現場標誌。</p><button class="button primary full" type="submit">儲存設定</button></form><h2>Drive Mode 執法提醒</h2><label class="form-field">前方提醒距離<select id="enforcementDistance">${[300,500,800,1000].map(v=>`<option value="${v}" ${v===state.settings.enforcementDistance?'selected':''}>${v} m</option>`).join('')}</select></label><label class="switch-row"><span>裝置支援時震動</span><input id="enforcementVibrate" type="checkbox" ${state.settings.vibrate?'checked':''}></label><p class="micro">距離、震動立即儲存。提示音沿用上方設定。道路速限尚無可靠 provider，因此「速限 + X」提醒尚不可用。方向未知會標示；平行道路與上下層道路仍可能誤判。</p><h2>加入 iPhone 主畫面</h2><p class="subtle">使用 Safari 開啟此網址，按分享，再選「加入主畫面」。下次直接點 GeoDeck 圖示。</p><h2>資料與隱私</h2><p class="micro">收藏及備註保存在這台裝置。使用定位、搜尋、天氣或路線時，相關座標會傳送給所選資料服務；沒有隊員背景追蹤。</p><p class="micro">地圖與路線：Google Maps<br>天氣／AQI：${sourceLink('https://open-meteo.com/','Open-Meteo')}／CAMS<br>雷達：${sourceLink('https://www.rainviewer.com/','RainViewer')}<br>雲圖：${sourceLink('https://www.earthdata.nasa.gov/','NASA GIBS')}／JMA／NOAA<br>公開影像：${sourceLink('https://www.twipcam.com/','twipcam')}<br>地震：${sourceLink('https://earthquake.usgs.gov/','USGS')}</p><p class="micro">GeoDeck ${VERSION}</p><button class="text-button" data-action="check-update">檢查更新</button>`,'PREFERENCES');$('enforcementDistance').onchange=e=>{state.settings.enforcementDistance=Number(e.target.value);write('geodeck.settings',state.settings)};$('enforcementVibrate').onchange=e=>{state.settings.vibrate=e.target.checked;write('geodeck.settings',state.settings)};$('settingsForm').onsubmit=e=>{e.preventDefault();const v=$('speedLimit').value;const next={...state.settings,speed:$('speedToggle').checked,limit:v===''?null:Number(v),voice:$('voiceToggle').checked,awake:$('awakeToggle').checked};if(next.limit!==null&&(!finite(next.limit)||next.limit<5||next.limit>200))return toast('請輸入 5–200 km/h 的提示門檻');if(write('geodeck.settings',next)){state.settings=next;if(next.speed){unlockAudio();startSpeed()}else stopSpeed();closePanel();toast('設定已儲存')}}}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('裝置不支援定位'));navigator.geolocation.getCurrentPosition(p=>{const point={lat:p.coords.latitude,lng:p.coords.longitude,title:'目前位置'};state.userPoint=point;if(state.map){locationMarker??=new google.maps.Marker({map:state.map,icon:{path:google.maps.SymbolPath.CIRCLE,scale:8,fillColor:'#a8bfd2',fillOpacity:1,strokeColor:'#fff',strokeWeight:2},zIndex:90});locationMarker.setPosition(point);accuracyCircle??=new google.maps.Circle({map:state.map,fillColor:'#8ea9be',fillOpacity:.1,strokeColor:'#a0b7cb',strokeOpacity:.4,strokeWeight:1,clickable:false});accuracyCircle.setCenter(point);accuracyCircle.setRadius(p.coords.accuracy)}resolve(point)},reject,{enableHighAccuracy:true,maximumAge:10000,timeout:12000})})}
async function locate(){if(!mapReady())return;$('locate').disabled=true;try{const p=await getPosition();state.map.panTo(p);state.map.setZoom(15)}catch{toast('無法取得定位，仍可搜尋地點；也可檢查 Safari 定位權限')}finally{$('locate').disabled=false}}
async function requestWake(){if(!state.settings.awake||!state.settings.speed||document.hidden||!navigator.wakeLock||wakeLock)return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>wakeLock=null)}catch{}}
function unlockAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audioContext??=new C();audioContext.resume()}catch{}}
function alertSpeed(){if(Date.now()-lastAlert<15000)return;lastAlert=Date.now();if(!state.settings.voice)return;try{if(audioContext?.state==='running'){const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=880;g.gain.value=.04;o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.18)}if('speechSynthesis'in window&&!speechSynthesis.speaking){const u=new SpeechSynthesisUtterance('請注意速度');u.lang='zh-TW';u.rate=1;speechSynthesis.speak(u)}}catch{}}
function startSpeed(){if(driveController?.active)return;if(watchId!==null||!navigator.geolocation)return;$('speedHud').classList.remove('hidden');$('speedValue').textContent='—';$('speedMeta').textContent='等待 GPS 定位';requestWake();watchId=navigator.geolocation.watchPosition(p=>{const speed=gpsSpeed(p,lastGps);lastGps=p;lastGpsAt=Date.now();$('speedValue').textContent=fmt(speed);$('speedMeta').textContent=speed===null?'GPS 精度不足':state.settings.limit!==null?'自訂提醒 '+state.settings.limit+' km/h':'GPS 精度約 '+Math.round(p.coords.accuracy)+' m';const over=speed!==null&&state.settings.limit!==null&&speed>state.settings.limit;$('speedHud').classList.toggle('over',over);if(over)alertSpeed()},()=>{$('speedValue').textContent='—';$('speedMeta').textContent='未取得定位';$('speedHud').classList.remove('over')},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function stopSpeed({hidden=false}={}){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;lastGps=null;lastGpsAt=0;wakeLock?.release();wakeLock=null;$('speedHud').classList.toggle('hidden',!hidden);$('speedHud').classList.remove('over');$('speedValue').textContent='—';$('speedMeta').textContent='背景已暫停'}
setInterval(()=>{if(watchId!==null&&lastGpsAt&&Date.now()-lastGpsAt>15000){$('speedValue').textContent='—';$('speedMeta').textContent='GPS 訊號已過期';$('speedHud').classList.remove('over')}},5000);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state.settings.speed)stopSpeed({hidden:true});stopCamera()}else if(state.settings.speed&&!driveController?.active)startSpeed()});
$('layers').onclick=()=>state.panel==='layers'?closePanel():renderLayers();$('routes').onclick=()=>state.panel==='routes'?closePanel():renderRoutes();$('favorites').onclick=()=>state.panel==='favorites'?closePanel():renderFavorites();$('field').onclick=renderField;$('settings').onclick=renderSettings;$('closePanel').onclick=closePanel;$('locate').onclick=locate;
$('centerWeather').onclick=()=>{if(!mapReady())return;const c=state.map.getCenter();selectLocation({lat:c.lat(),lng:c.lng(),title:'地圖中心'})};
$('radarPlay').onclick=()=>state.layers?.radarPlay();$('radarLatest').onclick=()=>state.layers?.radarLatest();$('radarRange').oninput=e=>{state.layers?.pauseRadar();state.layers?.radarAt(Number(e.target.value))};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel()});
$('searchForm').onsubmit=async e=>{e.preventDefault();const text=$('search').value.trim();if(!text||!mapReady())return;try{const p=await resolveLocation(text);$('search').blur();selectLocation(p,{pan:true})}catch{toast('找不到地點，請加上城市名稱或輸入經緯度')}};
$('panelBody').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.base){if(!mapReady())return;state.map.setMapTypeId(d.base);write('geodeck.base',d.base);renderLayers()}if(d.layer){if(!mapReady())return;const on=!state.layers.enabled.has(d.layer);b.setAttribute('aria-pressed',String(on));state.layers.set(d.layer,on);write('geodeck.layers',[...state.layers.enabled])}if(d.travel){state.routeSequence++;state.routeMode=d.travel;state.route=null;routeRenderer?.setMap(null);if($('routeSubmit'))$('routeSubmit').disabled=false;document.querySelectorAll('[data-travel]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.travel===d.travel)));$('routeResult').innerHTML='';renderExternalRoute()}if(d.routeIndex!==undefined)showRouteResult(Number(d.routeIndex));if(d.savedOpen!==undefined)selectLocation(state.saved[Number(d.savedOpen)],{pan:true});if(d.savedEdit!==undefined)editSaved(state.saved[Number(d.savedEdit)]);if(d.savedRoute!==undefined){state.selected=state.saved[Number(d.savedRoute)];renderRoutes()}if(d.savedDelete!==undefined){const index=Number(d.savedDelete),next=state.saved.filter((_,i)=>i!==index);if(write('geodeck.saved',next)){state.saved=next;renderFavorites();toast('已移除收藏')}}if(d.poi)loadPoi(d.poi);if(!d.action)return;switch(d.action){case'start-drive':startDrive(true);break;case'free-drive':startDrive(false);break;case'route-selected':renderRoutes();break;case'save-selected':if(state.selected)editSaved(state.selected);break;case'share-selected':shareSelected();break;case'nearby-cameras':if(!mapReady())break;closePanel();state.map.panTo(state.selected);state.map.setZoom(14);state.layers.set('camera',true);break;case'nearby-facilities':renderField();break;case'export-favorites':exportFavorites();break;case'clear-poi':clearPoi();if($('poiResults'))$('poiResults').innerHTML='';break;case'clear-route':state.route=null;state.routeSequence++;routeRenderer?.setMap(null);renderRoutes();break;case'check-update':checkUpdate();break}});
const darkStyle=[{elementType:'geometry',stylers:[{color:'#202c37'}]},{elementType:'labels.text.fill',stylers:[{color:'#bbc6d0'}]},{elementType:'labels.text.stroke',stylers:[{color:'#202c37'}]},{featureType:'administrative',elementType:'geometry',stylers:[{color:'#53606e'}]},{featureType:'poi',elementType:'geometry',stylers:[{color:'#273642'}]},{featureType:'poi',elementType:'labels.icon',stylers:[{visibility:'off'}]},{featureType:'poi.park',elementType:'geometry',stylers:[{color:'#213c36'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#465363'}]},{featureType:'road',elementType:'geometry.stroke',stylers:[{color:'#293744'}]},{featureType:'road.highway',elementType:'geometry',stylers:[{color:'#697a8b'}]},{featureType:'road.highway',elementType:'geometry.stroke',stylers:[{color:'#4b5a69'}]},{featureType:'transit',elementType:'geometry',stylers:[{color:'#364858'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#101f2c'}]},{featureType:'water',elementType:'labels.text.fill',stylers:[{color:'#7c9eb3'}]}];
function initMap(){const base=read('geodeck.base','roadmap');state.map=new google.maps.Map($('map'),{center:{lat:23.7,lng:120.95},zoom:7,disableDefaultUI:true,clickableIcons:false,gestureHandling:'greedy',mapTypeId:['roadmap','hybrid','terrain'].includes(base)?base:'roadmap',styles:darkStyle,colorScheme:google.maps.ColorScheme?.DARK,backgroundColor:'#17222e',renderingType:google.maps.RenderingType.RASTER,keyboardShortcuts:true});$('mapState').classList.add('hidden');geocoder=new google.maps.Geocoder();placesService=google.maps.places?.PlacesService?new google.maps.places.PlacesService(state.map):null;state.layers=createLayers(state.map,{status:updateLayerStatus,camera:showCamera,point:selectLocation,quake:showQuake,radarState:renderRadar});state.map.addListener('click',e=>!driveController?.active&&selectLocation({lat:e.latLng.lat(),lng:e.latLng.lng(),title:'選取位置'}));
if(google.maps.places?.Autocomplete){const ac=new google.maps.places.Autocomplete($('search'),{fields:['geometry','name','formatted_address','place_id','address_components']});ac.addListener('place_changed',()=>{const p=ac.getPlace(),l=p.geometry?.location;if(!l)return;$('search').blur();selectLocation({lat:l.lat(),lng:l.lng(),title:p.name||p.formatted_address||'搜尋位置',placeId:p.place_id,country:p.address_components?.find(x=>x.types.includes('country'))?.short_name||''},{pan:true})})}
const stored=read('geodeck.layers',[]);if(Array.isArray(stored))for(const id of stored.filter(x=>Object.hasOwn(state.layers.names,x)))state.layers.set(id,true);
const params=new URL(location.href).searchParams;const p={lat:Number(params.get('lat')),lng:Number(params.get('lng')),title:params.get('name')?.slice(0,120)||'分享的位置'};if(params.has('lat')&&params.has('lng')&&validPoint(p))selectLocation(p,{pan:true});
if(state.settings.speed&&navigator.permissions)navigator.permissions.query({name:'geolocation'}).then(r=>{if(r.state==='granted')startSpeed()}).catch(()=>{});
}
let mapLoadTimer;
function startDrive(withRoute){if(!mapReady())return;parkingController?.clear();const leg=withRoute&&state.routeMode==='driving'?state.route?.routes[state.routeIndex||0]?.legs[0]:null;if(withRoute&&!leg)return toast('請先取得開車路線');stopSpeed();suspendedLayers=[...(state.layers?.enabled||[])].filter(id=>id!=='traffic');for(const id of suspendedLayers)state.layers.set(id,false);driveController??=createDrive({map:()=>state.map,stripHtml,closePanel,unlockAudio,onStop:()=>{for(const id of suspendedLayers)state.layers.set(id,true);suspendedLayers=[];if(state.settings.speed)startSpeed()},notify:text=>{toast(text);try{if('speechSynthesis'in window&&!speechSynthesis.speaking){const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';speechSynthesis.speak(u)}}catch{}}});driveController.start(leg,{distance:state.settings.enforcementDistance,voice:state.settings.voice,vibrate:state.settings.vibrate,awake:state.settings.awake})}
function loadMap(){const key=window.KTAK_CONFIG?.GOOGLE_MAPS_API_KEY;if(!key)return mapFailure('目前沒有可用的地圖設定；收藏功能仍可使用。');window.__geodeckReady=()=>{clearTimeout(mapLoadTimer);try{initMap()}catch(e){console.error('GeoDeck map initialization failed',e.message);mapFailure('地圖初始化失敗，請重新開啟。')}};window.gm_authFailure=()=>{clearTimeout(mapLoadTimer);mapFailure('Google 地圖暫時無法提供服務，請稍後重試。')};const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key,libraries:'places',language:'zh-TW',v:'weekly',loading:'async',callback:'__geodeckReady'});s.async=true;s.onerror=()=>{clearTimeout(mapLoadTimer);mapFailure(navigator.onLine?'無法連接 Google 地圖，請確認網路後重試。':'目前離線，可透過下方「收藏」查看地點與備註。')};document.head.append(s);mapLoadTimer=setTimeout(()=>mapFailure('連線較慢，請確認網路後重試。收藏功能仍可使用。'),20000)}
function networkState(){$('offlineBanner').classList.toggle('hidden',navigator.onLine)}window.addEventListener('online',networkState);window.addEventListener('offline',networkState);networkState();
let swRegistration,updateRequested=false;
async function checkUpdate(){if(!swRegistration){toast('請重新開啟網址以取得最新版');return}await swRegistration.update();if(swRegistration.waiting){$('updateBanner').classList.remove('hidden')}else toast('已檢查更新，目前版本 '+VERSION)}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(r=>{swRegistration=r;if(r.waiting)$('updateBanner').classList.remove('hidden');r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('updateBanner').classList.remove('hidden')})});r.update().catch(()=>{})}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updateRequested)location.reload()})}
$('applyUpdate').onclick=()=>{if(swRegistration?.waiting){updateRequested=true;swRegistration.waiting.postMessage({type:'SKIP_WAITING'})}else location.reload()};
loadMap();
