export const VERSION='0.2.0';
export function finite(v){return typeof v==='number'&&Number.isFinite(v)}
export function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export function validPoint(p){return p&&finite(p.lat)&&finite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180}
export function parseCoordinates(s){const m=String(s).trim().match(/^(-?\d+(?:\.\d+)?)\s*[,，\s]\s*(-?\d+(?:\.\d+)?)$/);if(!m)return null;const p={lat:Number(m[1]),lng:Number(m[2])};return validPoint(p)?p:null}
export function haversine(a,b){const R=6371000,r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r,x=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export function gpsSpeed(position,previous){const c=position.coords;if(!finite(c.accuracy)||c.accuracy>60)return null;if(finite(c.speed)&&c.speed>=0&&c.speed<100)return c.speed*3.6;if(!previous)return null;const seconds=(position.timestamp-previous.timestamp)/1000;if(seconds<1||seconds>12||previous.coords.accuracy>60)return null;const distance=haversine({lat:c.latitude,lng:c.longitude},{lat:previous.coords.latitude,lng:previous.coords.longitude});if(distance<Math.max(5,(c.accuracy+previous.coords.accuracy)/2))return 0;const speed=distance/seconds*3.6;return speed<=250?speed:null}
export function aqiInfo(v){if(!finite(v))return{label:'無資料',color:'#8793a1'};if(v<=50)return{label:'良好',color:'#a4db82'};if(v<=100)return{label:'普通',color:'#efcf76'};if(v<=150)return{label:'對敏感族群不健康',color:'#f4a96f'};if(v<=200)return{label:'不健康',color:'#f88581'};if(v<=300)return{label:'非常不健康',color:'#ce9adc'};return{label:'危害',color:'#df8fa1'}}
export function weatherInfo(c){if(!finite(c))return['無資料','—'];if(c===0)return['晴','☀️'];if(c<=3)return['多雲','⛅'];if(c===45||c===48)return['霧','🌫️'];if(c>=95)return['雷雨','⛈️'];if(c>=71&&c<=77||c===85||c===86)return['降雪','🌨️'];if(c>=80)return['陣雨','🌦️'];return['降雨','🌧️']}
export function regionalProvider(p,country=''){if(country==='KR')return'naver';if(country==='CN')return'amap';return'google'}
export function wgsToGcj(p){if(p.lng<72.004||p.lng>137.8347||p.lat<0.8293||p.lat>55.8271)return p;const pi=Math.PI,x=p.lng-105,y=p.lat-35;let a=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));let b=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));a+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;a+=(20*Math.sin(y*pi)+40*Math.sin(y/3*pi))*2/3;a+=(160*Math.sin(y/12*pi)+320*Math.sin(y*pi/30))*2/3;b+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;b+=(20*Math.sin(x*pi)+40*Math.sin(x/3*pi))*2/3;b+=(150*Math.sin(x/12*pi)+300*Math.sin(x/30*pi))*2/3;const rad=p.lat/180*pi,magic=1-.00669342162296594323*Math.sin(rad)**2,sqrt=Math.sqrt(magic);a=a*180/((6378245*(1-.00669342162296594323))/(magic*sqrt)*pi);b=b*180/(6378245/sqrt*Math.cos(rad)*pi);return{lat:p.lat+a,lng:p.lng+b}}
export function navigationUrl({destination,origin,mode='driving',provider='google'}){if(!validPoint(destination))throw Error('Invalid destination');if(provider==='naver'){const m=mode==='transit'?'public':mode==='walking'?'walk':'car';const q=new URLSearchParams({dlat:destination.lat,dlng:destination.lng,dname:destination.title||'目的地',appname:'https://walther-p.github.io/KTAK-DEV/geodeck/'});if(validPoint(origin)){q.set('slat',origin.lat);q.set('slng',origin.lng);q.set('sname',origin.title||'出發地')}return'nmap://route/'+m+'?'+q}
if(provider==='amap'){const d=wgsToGcj(destination),q=new URLSearchParams({to:`${d.lng},${d.lat},${destination.title||'目的地'}`,mode:mode==='transit'?'bus':mode==='walking'?'walk':'car',src:'GeoDeck',callnative:'0'});if(validPoint(origin)){const o=wgsToGcj(origin);q.set('from',`${o.lng},${o.lat},${origin.title||'出發地'}`)}return'https://uri.amap.com/navigation?'+q}
const q=new URLSearchParams({api:'1',destination:`${destination.lat},${destination.lng}`,travelmode:mode});if(destination.placeId)q.set('destination_place_id',destination.placeId);if(validPoint(origin))q.set('origin',`${origin.lat},${origin.lng}`);if(mode==='driving')q.set('dir_action','navigate');return'https://www.google.com/maps/dir/?'+q}
export function normalizedSaved(raw){if(!Array.isArray(raw))return[];const seen=new Set();return raw.filter(validPoint).filter(p=>{const k=`${p.lat.toFixed(5)},${p.lng.toFixed(5)}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,200).map(p=>({id:String(p.id||`${p.lat.toFixed(5)},${p.lng.toFixed(5)}`),lat:p.lat,lng:p.lng,title:String(p.title||'收藏地點').slice(0,120),note:String(p.note||'').slice(0,4000),savedAt:p.savedAt||new Date().toISOString(),country:String(p.country||''),placeId:String(p.placeId||'')}))}
export function normalizeCameras(data){const rows=Array.isArray(data)?data:data.cameras;if(!Array.isArray(rows))throw Error('Invalid camera catalog');return rows.map(c=>({id:String(c.id||''),lat:Number(c.lat),lng:Number(c.lng??c.lon),name:String(c.name||'公開影像'),image:String(c.image??c.cam_url??''),source:'https://www.twipcam.com/cam/'+encodeURIComponent(String(c.id||''))})).filter(c=>validPoint(c)&&c.lat>18&&c.lat<28&&c.lng>115&&c.lng<125&&/^https:\/\//.test(c.image))}
export function cloudSource(lng){if(lng>=60||lng<=-160)return'Himawari_AHI_Band13_Clean_Infrared';if(lng<-95)return'GOES-West_ABI_Band13_Clean_Infrared';if(lng<-20)return'GOES-East_ABI_Band13_Clean_Infrared';return'MODIS_Terra_Cloud_Top_Temp_Day'}
