import {normalizeCameras,cloudSource,aqiInfo,finite} from './core.js?v=0.2.0';
export async function jsonFetch(url,timeout=15000,externalSignal){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout),abort=()=>c.abort();externalSignal?.addEventListener('abort',abort,{once:true});try{if(externalSignal?.aborted)throw new DOMException('Aborted','AbortError');const r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer);externalSignal?.removeEventListener('abort',abort)}}
const cache=new Map();
function tileImage(url){if(cache.has(url))return cache.get(url);const p=new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=()=>reject(Error('影像圖塊無法載入'));i.src=url});cache.set(url,p);p.catch(()=>cache.delete(url));if(cache.size>180)cache.delete(cache.keys().next().value);return p}
export function canvasTiles({url,nativeZoom=7,opacity=.7,onError}){return{tileSize:new google.maps.Size(256,256),maxZoom:22,minZoom:0,getTile(coord,zoom,doc){const c=doc.createElement('canvas');c.width=c.height=256;c.style.opacity=String(opacity);c.setAttribute('aria-hidden','true');const world=2**zoom;if(coord.y<0||coord.y>=world)return c;const x=(coord.x%world+world)%world,nz=Math.min(zoom,nativeZoom),scale=2**(zoom-nz);tileImage(url(Math.floor(x/scale),Math.floor(coord.y/scale),nz)).then(img=>{if(c._released)return;const w=img.width/scale,h=img.height/scale;c.getContext('2d').drawImage(img,(x%scale)*w,(coord.y%scale)*h,w,h,0,0,256,256)}).catch(()=>{if(!c._released)onError?.()});return c},releaseTile(t){t._released=true;t.width=t.height=0}}}
export function createLayers(map,{status,camera,point,quake,radarState}){
 const enabled=new Set(),overlays=new Map(),markers={camera:[],aqi:[],earthquake:[]},tokens={radar:0,cloud:0,camera:0,aqi:0,earthquake:0};
 const traffic=new google.maps.TrafficLayer();let cameraList=null,catalogTime='',radarData=null,frame=0,playTimer=null,cloudDoc=null,cloudLoaded=0,currentCloud='',aqiLast='',aqiAt=0,aqiTimer,quakes=[],lastIdle;
 const names={traffic:'即時路況',radar:'雷達回波',cloud:'衛星雲圖',camera:'台灣即時影像',aqi:'空氣品質',earthquake:'近期地震'};
 const say=(id,message)=>status(id,message,enabled.has(id));
 function removeOverlay(id){const layer=overlays.get(id);if(layer){for(let i=map.overlayMapTypes.getLength()-1;i>=0;i--)if(map.overlayMapTypes.getAt(i)===layer)map.overlayMapTypes.removeAt(i);overlays.delete(id)}}
 function putOverlay(id,layer){removeOverlay(id);overlays.set(id,layer);map.overlayMapTypes.push(layer)}
 function clearMarkers(id){markers[id].forEach(m=>m.setMap(null));markers[id]=[]}
 function layerError(id){let reported=false;return()=>{if(reported||!enabled.has(id))return;reported=true;say(id,names[id]+' · 部分影像未載入，可關閉後重試')}}
 function showRadar(index){if(!radarData||!enabled.has('radar'))return;frame=index;const f=radarData.radar.past[frame];const host=radarData.host;putOverlay('radar',canvasTiles({nativeZoom:7,opacity:.76,url:(x,y,z)=>`${host}${f.path}/256/${z}/${x}/${y}/2/1_1.png`,onError:layerError('radar')}));const age=Date.now()-f.time*1000,label=new Date(f.time*1000).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'});say('radar','雷達 '+label+(age>3*3600000?' · 資料較舊':''));radarState({frames:radarData.radar.past,index:frame,playing:!!playTimer})}
 function pauseRadar(){if(playTimer)clearInterval(playTimer);playTimer=null;if(radarData)radarState({frames:radarData.radar.past,index:frame,playing:false})}
 async function loadRadar(){const t=++tokens.radar;say('radar','雷達載入中…');const d=await jsonFetch('https://api.rainviewer.com/public/weather-maps.json');if(t!==tokens.radar||!enabled.has('radar'))return;if(!d.radar?.past?.length||!/^https:\/\/([a-z0-9-]+\.)*rainviewer\.com$/.test(d.host))throw Error('雷達來源無有效資料');radarData=d;putOverlay('radar-coverage',canvasTiles({nativeZoom:7,opacity:.35,url:(x,y,z)=>`${d.host}/v2/coverage/0/256/${z}/${x}/${y}/0/0_0.png`}));showRadar(d.radar.past.length-1)}
 async function loadCloud(){const t=++tokens.cloud;const id=cloudSource(map.getCenter().lng());if(id===currentCloud&&overlays.has('cloud'))return;say('cloud','衛星雲圖載入中…');if(!cloudDoc||Date.now()-cloudLoaded>15*60000){const c=new AbortController(),timeout=setTimeout(()=>c.abort(),30000);try{const r=await fetch('https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/1.0.0/WMTSCapabilities.xml',{signal:c.signal});if(!r.ok)throw Error('NASA 暫無回應');cloudDoc=new DOMParser().parseFromString(await r.text(),'application/xml');cloudLoaded=Date.now()}finally{clearTimeout(timeout)}}if(!enabled.has('cloud')||t!==tokens.cloud)return;const layer=[...cloudDoc.getElementsByTagNameNS('*','Layer')].find(l=>[...l.children].some(e=>e.localName==='Identifier'&&e.textContent===id));if(!layer)throw Error('雲圖未涵蓋');const dimension=[...layer.getElementsByTagNameNS('*','Dimension')][0];const time=dimension?.getElementsByTagNameNS('*','Default')[0]?.textContent;const matrix=layer.getElementsByTagNameNS('*','TileMatrixSet')[0]?.textContent;if(!time||!matrix)throw Error('雲圖時間無法確認');currentCloud=id;const daily=!time.includes('T'),source=id.startsWith('Himawari')?'向日葵':id.startsWith('GOES-East')?'GOES 東':id.startsWith('GOES-West')?'GOES 西':'全球日雲圖';const label=daily?time+' UTC（日資料）':new Date(time).toLocaleString('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});putOverlay('cloud',canvasTiles({nativeZoom:6,opacity:.62,url:(x,y,z)=>`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${id}/default/${time}/${matrix}/${z}/${y}/${x}.png`,onError:layerError('cloud')}));say('cloud',source+' '+label+(Date.now()-Date.parse(time)>(daily?72:4)*3600000?' · 資料較舊':''))}
 async function loadCameras(){const t=++tokens.camera;say('camera','載入台灣公開影像…');if(!cameraList){try{const d=await jsonFetch('https://www.twipcam.com/api/v1/cam-list.json',6000);cameraList=normalizeCameras(d);catalogTime=new Date().toISOString()}catch{const r=await fetch('./data/cameras-tw.json.gz');if(!r.ok)throw Error('影像目錄暫時無法載入');const bytes=new Uint8Array(await r.arrayBuffer());const stream=new Blob([bytes]).stream();const d=await new Response(bytes[0]===31&&bytes[1]===139?stream.pipeThrough(new DecompressionStream('gzip')):stream).json();cameraList=normalizeCameras(d);catalogTime=d.updatedAt}}if(t!==tokens.camera||!enabled.has('camera'))return;renderCameras()}
 function renderCameras(){clearMarkers('camera');if(!enabled.has('camera')||!cameraList)return;const bounds=map.getBounds(),projection=map.getProjection();if(!bounds||!projection)return;const groups=new Map(),scale=2**map.getZoom();for(const c of cameraList){if(!bounds.contains({lat:c.lat,lng:c.lng}))continue;const p=projection.fromLatLngToPoint(new google.maps.LatLng(c.lat,c.lng)),k=Math.floor(p.x*scale/62)+':'+Math.floor(p.y*scale/62);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(c)}let count=0;for(const items of [...groups.values()].slice(0,180)){const many=items.length>1,c=items[0],pos={lat:items.reduce((s,x)=>s+x.lat,0)/items.length,lng:items.reduce((s,x)=>s+x.lng,0)/items.length};count+=items.length;const m=new google.maps.Marker({map,position:pos,title:many?`${items.length} 支公開影像，點選放大`:c.name,icon:{path:google.maps.SymbolPath.CIRCLE,scale:many?19:16,fillColor:'#2c4458',fillOpacity:1,strokeColor:'#b8d2e8',strokeWeight:1.4},label:{text:many?String(items.length):'▣',color:'#f0f7ff',fontSize:many?'12px':'17px',fontWeight:'600'},zIndex:many?30:20});m.addListener('click',()=>{if(many&&map.getZoom()<19){map.panTo(pos);map.setZoom(Math.min(19,map.getZoom()+2))}else camera(c,items,catalogTime)});markers.camera.push(m)}say('camera',count?`台灣影像 ${count.toLocaleString()} 支 · 目錄 ${String(catalogTime).slice(0,10)}`:'目前範圍沒有已收錄影像 · 可移至台灣')}
 async function loadAqi(force=false){if(!enabled.has('aqi'))return;if(map.getZoom()<5){clearMarkers('aqi');say('aqi','空氣品質 · 放大到城市查看');return}const center=map.getCenter(),bounds=map.getBounds();if(!bounds)return;const key=center.lat().toFixed(1)+','+center.lng().toFixed(1)+','+Math.floor(map.getZoom()/2);if(!force&&key===aqiLast&&Date.now()-aqiAt<15*60000)return;const t=++tokens.aqi;aqiLast=key;aqiAt=Date.now();clearMarkers('aqi');say('aqi','空氣品質格點載入中…');const ne=bounds.getNorthEast(),sw=bounds.getSouthWest(),spanLat=Math.min(2,Math.abs(ne.lat()-sw.lat())*.23),spanLng=Math.min(2,Math.abs(ne.lng()-sw.lng())*.23);const points=[[-1,-1],[-1,1],[0,0],[1,-1],[1,1]].map(([a,b])=>({lat:Math.max(-85,Math.min(85,center.lat()+a*spanLat)),lng:((center.lng()+b*spanLng+540)%360)-180}));const q=new URLSearchParams({latitude:points.map(x=>x.lat.toFixed(4)).join(','),longitude:points.map(x=>x.lng.toFixed(4)).join(','),current:'us_aqi,pm2_5',timeformat:'unixtime'});const data=await jsonFetch('https://air-quality-api.open-meteo.com/v1/air-quality?'+q);if(t!==tokens.aqi||!enabled.has('aqi'))return;const rows=Array.isArray(data)?data:[data];let valid=0;rows.forEach((d,i)=>{const v=d.current?.us_aqi;if(!finite(v)||!points[i])return;const info=aqiInfo(v),m=new google.maps.Marker({map,position:points[i],title:`模式格點 AQI ${Math.round(v)}，${info.label}`,icon:{path:google.maps.SymbolPath.CIRCLE,scale:22,fillColor:info.color,fillOpacity:.95,strokeColor:'#182431',strokeWeight:2},label:{text:String(Math.round(v)),color:'#182431',fontSize:'13px',fontWeight:'700'},zIndex:50});m.addListener('click',()=>point({...points[i],title:'空氣品質模式格點'}));markers.aqi.push(m);valid++});say('aqi',valid?'AQI 模式格點 · 美國標準 · Open-Meteo':'目前範圍無有效空氣品質資料')}
 async function loadQuakes(){const t=++tokens.earthquake;say('earthquake','地震資料載入中…');const d=await jsonFetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson');if(t!==tokens.earthquake||!enabled.has('earthquake'))return;quakes=(d.features||[]).filter(f=>f.geometry?.coordinates?.length>=2);renderQuakes();say('earthquake',`USGS 過去 7 天 · M2.5+ · ${new Date(d.metadata.generated).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`)}
 function renderQuakes(){clearMarkers('earthquake');if(!enabled.has('earthquake'))return;const bounds=map.getBounds();if(!bounds)return;for(const q of quakes){const [lng,lat,depth]=q.geometry.coordinates;if(!bounds.contains({lat,lng}))continue;const m=new google.maps.Marker({map,position:{lat,lng},title:q.properties.title,icon:{path:google.maps.SymbolPath.CIRCLE,scale:Math.max(8,Math.min(24,q.properties.mag*3)),fillColor:'#ed9a71',fillOpacity:.5,strokeColor:'#ffcba9',strokeWeight:1.5},label:{text:String(q.properties.mag),fontSize:'11px',color:'#fff'},zIndex:10});m.addListener('click',()=>quake({lat,lng,depth,...q.properties}));markers.earthquake.push(m)}}
 async function set(id,on){if(on)enabled.add(id);else enabled.delete(id);if(!on){tokens[id]++;say(id,'');if(id==='traffic')traffic.setMap(null);if(id==='radar'){pauseRadar();removeOverlay('radar');removeOverlay('radar-coverage');radarState(null)}else removeOverlay(id);if(markers[id])clearMarkers(id);if(id==='cloud')currentCloud='';return}try{if(id==='traffic'){traffic.setMap(map);say(id,'Google 即時路況')}if(id==='radar')await loadRadar();if(id==='cloud')await loadCloud();if(id==='camera')await loadCameras();if(id==='aqi')await loadAqi(true);if(id==='earthquake')await loadQuakes()}catch(e){if(enabled.has(id))say(id,names[id]+' · 暫時無法載入，關閉後可重試')}}
 map.addListener('idle',()=>{clearTimeout(lastIdle);lastIdle=setTimeout(()=>{if(enabled.has('camera'))renderCameras();if(enabled.has('earthquake'))renderQuakes();if(enabled.has('cloud'))loadCloud().catch(()=>say('cloud','衛星雲圖暫時無法載入'));clearTimeout(aqiTimer);if(enabled.has('aqi'))aqiTimer=setTimeout(()=>loadAqi().catch(()=>say('aqi','空氣品質暫時無法載入')),900)},160)});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseRadar()});
 return{enabled,set,names,radarAt:showRadar,radarLatest:()=>loadRadar().catch(()=>say('radar','雷達更新失敗')),radarPlay(){if(playTimer){pauseRadar();return}if(!radarData)return;playTimer=setInterval(()=>showRadar((frame+1)%radarData.radar.past.length),900);showRadar(frame)},pauseRadar};
}
